import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import SideBar from '@/components/SideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn('min-h-screen w-full bg-zinc-900 text-white flex ', inter.className)}>
        <SideBar
          domains={[
            'ads',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
            'asd',
          ]}
        />
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  )
}
